// <auto-generated />
namespace BookWriterTool.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddExternalUserDEtails : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddExternalUserDEtails));
        
        string IMigrationMetadata.Id
        {
            get { return "201312290942245_AddExternalUserDEtails"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
