// <auto-generated />
namespace BookWriterTool.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Initialstate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Initialstate));
        
        string IMigrationMetadata.Id
        {
            get { return "201411302012548_Initialstate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
