//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5472
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <remarks/>

[System.Xml.Serialization.XmlRootAttribute("book")]
public partial class book {
    
    private Chapters chaptersField;

    private string idField;

   //[System.Xml.Serialization.XmlArrayItemAttribute("chapters", IsNullable = false)]
    public Chapters chapters {
        get {
            return this.chaptersField;
        }
        set {
            this.chaptersField = value;
        }
    }
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }
}


[System.Xml.Serialization.XmlTypeAttribute("chapters")]
public partial class Chapters {
    
    private Chapter chapterField;

    private string idField;

   // [System.Xml.Serialization.XmlArrayItemAttribute("chapter", IsNullable = false)]
    public Chapter chapter {
        get {
            return this.chapterField;
        }
        set {
            this.chapterField = value;
        }
    }
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }
}


[System.Xml.Serialization.XmlTypeAttribute("chapter")]
public partial class Chapter {
    
    private Pages pagesField;
    
    private string idField;

 // [System.Xml.Serialization.XmlArrayItemAttribute("pages", IsNullable = false)]
    public Pages pages {
        get {
            return this.pagesField;
        }
        set {
            this.pagesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}


[System.Xml.Serialization.XmlTypeAttribute("pages")]
public partial class Pages {
    
    private Page pageField;

    private string idField;

   //[System.Xml.Serialization.XmlArrayItemAttribute("page", IsNullable = false)]
    public Page page {
        get {
            return this.pageField;
        }
        set {
            this.pageField = value;
        }
    }
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }
}


[System.Xml.Serialization.XmlTypeAttribute("page")]
public partial class Page {
    
    private Frame[] framesField;
    
    private string idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("frame", IsNullable=false)]
    public Frame[] frames {
        get {
            return this.framesField;
        }
        set {
            this.framesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}


[System.Xml.Serialization.XmlTypeAttribute("frame")]
public partial class Frame {
    
    private string sceneField;
    
    private Content[] contentsField;
    
    private string idField;
    
    private string bordertypeField;
    
    /// <remarks/>
    public string scene {
        get {
            return this.sceneField;
        }
        set {
            this.sceneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("content", IsNullable=false)]
    public Content[] contents {
        get {
            return this.contentsField;
        }
        set {
            this.contentsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string bordertype {
        get {
            return this.bordertypeField;
        }
        set {
            this.bordertypeField = value;
        }
    }
}


[System.Xml.Serialization.XmlTypeAttribute("content")]
public partial class Content {
    
    private Object[] objectsField;
    
    private ContentChoice choiceField;
    
    private string targetField;
    
    private string typeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("object", IsNullable=false)]
    public Object[] objects {
        get {
            return this.objectsField;
        }
        set {
            this.objectsField = value;
        }
    }
    
    /// <remarks/>
    public ContentChoice choice {
        get {
            return this.choiceField;
        }
        set {
            this.choiceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string target {
        get {
            return this.targetField;
        }
        set {
            this.targetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}


[System.Xml.Serialization.XmlTypeAttribute("object")]
public partial class Object {
    
    private string typeField;
    
    private string idField;
    
    private string animationField;
    
    private string stringField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string animation {
        get {
            return this.animationField;
        }
        set {
            this.animationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string @string {
        get {
            return this.stringField;
        }
        set {
            this.stringField = value;
        }
    }
}

[System.Xml.Serialization.XmlTypeAttribute("choice")]
public partial class ContentChoice {
    
    private ContentChoiceQuestion questionField;
    
    private ContentChoicePositive positiveField;
    
    private ContentChoiceNegative negativeField;
    
    private string ownerField;
    
    /// <remarks/>
    public ContentChoiceQuestion question {
        get {
            return this.questionField;
        }
        set {
            this.questionField = value;
        }
    }
    
    /// <remarks/>
    public ContentChoicePositive positive {
        get {
            return this.positiveField;
        }
        set {
            this.positiveField = value;
        }
    }
    
    /// <remarks/>
    public ContentChoiceNegative negative {
        get {
            return this.negativeField;
        }
        set {
            this.negativeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string owner {
        get {
            return this.ownerField;
        }
        set {
            this.ownerField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ContentChoiceQuestion {
    
    private string idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }
}


[System.Xml.Serialization.XmlTypeAttribute("positive")]
public partial class ContentChoicePositive {
    
    private ContentChoicePositiveText textField;
    
    private ContentChoicePositiveResult resultField;
    
    /// <remarks/>
    public ContentChoicePositiveText text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
    
    /// <remarks/>
    public ContentChoicePositiveResult result {
        get {
            return this.resultField;
        }
        set {
            this.resultField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ContentChoicePositiveText {
    
    private string idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}


[System.Xml.Serialization.XmlTypeAttribute("result")]
public partial class ContentChoicePositiveResult {
    
    private ContentChoicePositiveResultSuccess successField;
    
    private ContentChoicePositiveResultFailed failedField;
    
    /// <remarks/>
    public ContentChoicePositiveResultSuccess success {
        get {
            return this.successField;
        }
        set {
            this.successField = value;
        }
    }
    
    /// <remarks/>
    public ContentChoicePositiveResultFailed failed {
        get {
            return this.failedField;
        }
        set {
            this.failedField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ContentChoicePositiveResultSuccess {
    
    private string gotoField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string @goto {
        get {
            return this.gotoField;
        }
        set {
            this.gotoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ContentChoicePositiveResultFailed {
    
    private string gotoField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string @goto {
        get {
            return this.gotoField;
        }
        set {
            this.gotoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ContentChoiceNegative {
    
    private ContentChoiceNegativeText textField;
    
    private ContentChoiceNegativeResult resultField;
    
    /// <remarks/>
    public ContentChoiceNegativeText text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
    
    /// <remarks/>
    public ContentChoiceNegativeResult result {
        get {
            return this.resultField;
        }
        set {
            this.resultField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ContentChoiceNegativeText {
    
    private string idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ContentChoiceNegativeResult {
    
    private ContentChoiceNegativeResultSuccess successField;
    
    private ContentChoiceNegativeResultFailed failedField;
    
    /// <remarks/>
    public ContentChoiceNegativeResultSuccess success {
        get {
            return this.successField;
        }
        set {
            this.successField = value;
        }
    }
    
    /// <remarks/>
    public ContentChoiceNegativeResultFailed failed {
        get {
            return this.failedField;
        }
        set {
            this.failedField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ContentChoiceNegativeResultSuccess {
    
    private string gotoField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string @goto {
        get {
            return this.gotoField;
        }
        set {
            this.gotoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ContentChoiceNegativeResultFailed {
    
    private string gotoField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string @goto {
        get {
            return this.gotoField;
        }
        set {
            this.gotoField = value;
        }
    }
}
